#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetOrder
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="JmgjjPreliminary")]
	public partial class OrderDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertA033PreFetch(A033PreFetch instance);
    partial void UpdateA033PreFetch(A033PreFetch instance);
    partial void DeleteA033PreFetch(A033PreFetch instance);
    #endregion
		
		public OrderDataClassesDataContext() : 
				base(global::GetOrder.Properties.Settings.Default.JmgjjPreliminaryConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OrderDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrderDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrderDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrderDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<A033PreFetch> A033PreFetches
		{
			get
			{
				return this.GetTable<A033PreFetch>();
			}
		}
		
		public System.Data.Linq.Table<View_PreUnitBusiness> View_PreUnitBusinesses
		{
			get
			{
				return this.GetTable<View_PreUnitBusiness>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.A033PreFetch")]
	public partial class A033PreFetch : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _responsNum;
		
		private System.Nullable<int> _areaCode;
		
		private System.Nullable<int> _aId;
		
		private System.Nullable<int> _uId;
		
		private string _account;
		
		private string _idCard;
		
		private string _tel;
		
		private string _fetchType;
		
		private System.Nullable<decimal> _fetchMoney;
		
		private string _status;
		
		private string _filePath;
		
		private System.Data.Linq.Binary _tsp;
		
		private System.Nullable<System.DateTime> _ondate;
		
		private string _editor;
		
		private string _des;
		
		private System.Nullable<System.DateTime> _edittime;
		
		private string _auditor;
		
		private System.Nullable<System.DateTime> _audittime;
		
		private bool _isdel;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnresponsNumChanging(string value);
    partial void OnresponsNumChanged();
    partial void OnareaCodeChanging(System.Nullable<int> value);
    partial void OnareaCodeChanged();
    partial void OnaIdChanging(System.Nullable<int> value);
    partial void OnaIdChanged();
    partial void OnuIdChanging(System.Nullable<int> value);
    partial void OnuIdChanged();
    partial void OnaccountChanging(string value);
    partial void OnaccountChanged();
    partial void OnidCardChanging(string value);
    partial void OnidCardChanged();
    partial void OntelChanging(string value);
    partial void OntelChanged();
    partial void OnfetchTypeChanging(string value);
    partial void OnfetchTypeChanged();
    partial void OnfetchMoneyChanging(System.Nullable<decimal> value);
    partial void OnfetchMoneyChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OnfilePathChanging(string value);
    partial void OnfilePathChanged();
    partial void OntspChanging(System.Data.Linq.Binary value);
    partial void OntspChanged();
    partial void OnondateChanging(System.Nullable<System.DateTime> value);
    partial void OnondateChanged();
    partial void OneditorChanging(string value);
    partial void OneditorChanged();
    partial void OndesChanging(string value);
    partial void OndesChanged();
    partial void OnedittimeChanging(System.Nullable<System.DateTime> value);
    partial void OnedittimeChanged();
    partial void OnauditorChanging(string value);
    partial void OnauditorChanged();
    partial void OnaudittimeChanging(System.Nullable<System.DateTime> value);
    partial void OnaudittimeChanged();
    partial void OnisdelChanging(bool value);
    partial void OnisdelChanged();
    #endregion
		
		public A033PreFetch()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_responsNum", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string responsNum
		{
			get
			{
				return this._responsNum;
			}
			set
			{
				if ((this._responsNum != value))
				{
					this.OnresponsNumChanging(value);
					this.SendPropertyChanging();
					this._responsNum = value;
					this.SendPropertyChanged("responsNum");
					this.OnresponsNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaCode", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> areaCode
		{
			get
			{
				return this._areaCode;
			}
			set
			{
				if ((this._areaCode != value))
				{
					this.OnareaCodeChanging(value);
					this.SendPropertyChanging();
					this._areaCode = value;
					this.SendPropertyChanged("areaCode");
					this.OnareaCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aId", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> aId
		{
			get
			{
				return this._aId;
			}
			set
			{
				if ((this._aId != value))
				{
					this.OnaIdChanging(value);
					this.SendPropertyChanging();
					this._aId = value;
					this.SendPropertyChanged("aId");
					this.OnaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uId", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> uId
		{
			get
			{
				return this._uId;
			}
			set
			{
				if ((this._uId != value))
				{
					this.OnuIdChanging(value);
					this.SendPropertyChanging();
					this._uId = value;
					this.SendPropertyChanged("uId");
					this.OnuIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_account", DbType="NVarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string account
		{
			get
			{
				return this._account;
			}
			set
			{
				if ((this._account != value))
				{
					this.OnaccountChanging(value);
					this.SendPropertyChanging();
					this._account = value;
					this.SendPropertyChanged("account");
					this.OnaccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCard", DbType="NVarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string idCard
		{
			get
			{
				return this._idCard;
			}
			set
			{
				if ((this._idCard != value))
				{
					this.OnidCardChanging(value);
					this.SendPropertyChanging();
					this._idCard = value;
					this.SendPropertyChanged("idCard");
					this.OnidCardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this.OntelChanging(value);
					this.SendPropertyChanging();
					this._tel = value;
					this.SendPropertyChanged("tel");
					this.OntelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fetchType", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string fetchType
		{
			get
			{
				return this._fetchType;
			}
			set
			{
				if ((this._fetchType != value))
				{
					this.OnfetchTypeChanging(value);
					this.SendPropertyChanging();
					this._fetchType = value;
					this.SendPropertyChanged("fetchType");
					this.OnfetchTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fetchMoney", DbType="Decimal(18,2)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> fetchMoney
		{
			get
			{
				return this._fetchMoney;
			}
			set
			{
				if ((this._fetchMoney != value))
				{
					this.OnfetchMoneyChanging(value);
					this.SendPropertyChanging();
					this._fetchMoney = value;
					this.SendPropertyChanged("fetchMoney");
					this.OnfetchMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filePath", DbType="NVarChar(500)", UpdateCheck=UpdateCheck.Never)]
		public string filePath
		{
			get
			{
				return this._filePath;
			}
			set
			{
				if ((this._filePath != value))
				{
					this.OnfilePathChanging(value);
					this.SendPropertyChanging();
					this._filePath = value;
					this.SendPropertyChanged("filePath");
					this.OnfilePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tsp", AutoSync=AutoSync.Always, DbType="rowversion", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary tsp
		{
			get
			{
				return this._tsp;
			}
			set
			{
				if ((this._tsp != value))
				{
					this.OntspChanging(value);
					this.SendPropertyChanging();
					this._tsp = value;
					this.SendPropertyChanged("tsp");
					this.OntspChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ondate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> ondate
		{
			get
			{
				return this._ondate;
			}
			set
			{
				if ((this._ondate != value))
				{
					this.OnondateChanging(value);
					this.SendPropertyChanging();
					this._ondate = value;
					this.SendPropertyChanged("ondate");
					this.OnondateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_editor", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string editor
		{
			get
			{
				return this._editor;
			}
			set
			{
				if ((this._editor != value))
				{
					this.OneditorChanging(value);
					this.SendPropertyChanging();
					this._editor = value;
					this.SendPropertyChanged("editor");
					this.OneditorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_des", DbType="NVarChar(200)", UpdateCheck=UpdateCheck.Never)]
		public string des
		{
			get
			{
				return this._des;
			}
			set
			{
				if ((this._des != value))
				{
					this.OndesChanging(value);
					this.SendPropertyChanging();
					this._des = value;
					this.SendPropertyChanged("des");
					this.OndesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edittime", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> edittime
		{
			get
			{
				return this._edittime;
			}
			set
			{
				if ((this._edittime != value))
				{
					this.OnedittimeChanging(value);
					this.SendPropertyChanging();
					this._edittime = value;
					this.SendPropertyChanged("edittime");
					this.OnedittimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auditor", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string auditor
		{
			get
			{
				return this._auditor;
			}
			set
			{
				if ((this._auditor != value))
				{
					this.OnauditorChanging(value);
					this.SendPropertyChanging();
					this._auditor = value;
					this.SendPropertyChanged("auditor");
					this.OnauditorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_audittime", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> audittime
		{
			get
			{
				return this._audittime;
			}
			set
			{
				if ((this._audittime != value))
				{
					this.OnaudittimeChanging(value);
					this.SendPropertyChanging();
					this._audittime = value;
					this.SendPropertyChanged("audittime");
					this.OnaudittimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isdel", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool isdel
		{
			get
			{
				return this._isdel;
			}
			set
			{
				if ((this._isdel != value))
				{
					this.OnisdelChanging(value);
					this.SendPropertyChanging();
					this._isdel = value;
					this.SendPropertyChanged("isdel");
					this.OnisdelChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_PreUnitBusiness")]
	public partial class View_PreUnitBusiness
	{
		
		private string _uaccount;
		
		private string _status;
		
		private System.Nullable<System.DateTime> _audittime;
		
		private System.Nullable<bool> _isdel;
		
		private string _responsNum;
		
		private int _areaCode;
		
		public View_PreUnitBusiness()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uaccount", DbType="NVarChar(50)")]
		public string uaccount
		{
			get
			{
				return this._uaccount;
			}
			set
			{
				if ((this._uaccount != value))
				{
					this._uaccount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NVarChar(50)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_audittime", DbType="DateTime")]
		public System.Nullable<System.DateTime> audittime
		{
			get
			{
				return this._audittime;
			}
			set
			{
				if ((this._audittime != value))
				{
					this._audittime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isdel", DbType="Bit")]
		public System.Nullable<bool> isdel
		{
			get
			{
				return this._isdel;
			}
			set
			{
				if ((this._isdel != value))
				{
					this._isdel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_responsNum", CanBeNull=false)]
		public string responsNum
		{
			get
			{
				return this._responsNum;
			}
			set
			{
				if ((this._responsNum != value))
				{
					this._responsNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaCode")]
		public int areaCode
		{
			get
			{
				return this._areaCode;
			}
			set
			{
				if ((this._areaCode != value))
				{
					this._areaCode = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
